# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='customer_id',
            field=models.IntegerField(default=121212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='order_number',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
